### ISSUE TITLE
How to revert back?

### ISSUE THREAD

**Issue by mreduar** [semazurek/ET-Optimizer#20]
I would like to revert all the changes that this software makes. Since my PC began to have behaviors that I did not want when running this program, such as some applications do not start with Windows as docker, and now I have to run many programs as administrator for them to work, otherwise they do not run.
How can I reverse everything this program does?

**Comment by semazurek** [comment]
rstrui.exe -> Select ET-RestorePoint or ET Script (main menu - Recover/Restore Option)
