### ISSUE TITLE
Virus Total Score: 43/70

### ISSUE THREAD

**Issue by Suleman-Elahi** [semazurek/ET-Optimizer#22]
![image](https://github.com/semazurek/ET-Optimizer/assets/24384996/9cea1e61-b592-4fcb-a978-4c53f62a39ea)

https://www.virustotal.com/gui/file/2911ded6b3f03148133be69e4e9ee2aabdaf744df14bb994e81de3a5a5f4d16b

Is it safe to execute?

**Comment by semazurek** [comment]
It's safe, I try my best, but antiviruses always falsely detect it as a threat when converting from .ps1 to .exe.

Try to use the regular .ps1 version, which also may require disabling your antivirus and always make your own backup.
