### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Bam810bam321** [semazurek/ET-Optimizer#23]
![image](https://github.com/semazurek/ET-Optimizer/assets/67829250/ed05359d-258f-439f-9035-617e8c5b7513)

**Comment by semazurek** [comment]
Set-ExecutionPolicy RemoteSigned looks lukę doesnt work try other powershell Window or run script in fresh new after that command and should work IF not something in your Windows is blocking that.

**Comment by semazurek** [comment]
+ Try update, connexting Windows to internet
