### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by D1mar0n** [semazurek/ET-Optimizer#24]
Hello! When I run the executable file, I receive a notification that the NOLP.txt file is missing next to ET-Optimizer.exe. Further operation of the script is not possible. How to fix this? 

### 

[Error text.txt](https://github.com/user-attachments/files/16975872/Error.text.txt)

https://github.com/user-attachments/assets/3cc8a537-5ba9-4175-ba93-4ed77b07d638

**Comment by semazurek** [comment]
Здарова )
First of all try to copy ET.exe to Desktop or other folder and re run.
Check if your antivirus silently may block creating NOLP.txt - this file is temp help file to count maximum amount of logical CPU cores.

I was testing on 2 laptops and newest version doesnt crash like you show but I will look for it.

**Comment by D1mar0n** [comment]
Thanks for the answer. Antivirus is turned off. I started it from another drive, not the system one. Now I'll try to run it from the desktop. I will write about the result later.

**Comment by D1mar0n** [comment]
I tried to launch from the desktop - the result is the same... The file is not created...

**Comment by semazurek** [comment]
OK...., I'll take a look at it and install 2 of 32 bit virtual machines for the test (Windows 10 and 8.1).
ок, я посмотрю и установлю для теста 2 32-битные виртуальные машины (Windows 10 и 8.1).

**Comment by D1mar0n** [comment]
> OK...., I'll take a look at it and install 2 of 32 bit virtual machines for the test (Windows 10 and 8.1). ок, я посмотрю и установлю для теста 2 32-битные виртуальные машины (Windows 10 и 8.1).

My virtual machine is 64 bit. There is also Windows 11, the same as my installed system, now for fun I’ll try to run it on it.

**Comment by semazurek** [comment]
Простите, но вы используете последнюю версию, загруженную здесь? 
forgive me but are you using the latest version downloaded here ?

trying to find the source of the problem in code and tests....

**Comment by semazurek** [comment]
![{56EE98D0-7D96-4E59-9C2E-140CFAAA2483}](https://github.com/user-attachments/assets/c52ee2ea-54da-413d-838f-7a56250ae72e)
Windows 8.1 32bit (No Antivirus) works all expect Adwcleaner. no errors.

**Comment by D1mar0n** [comment]
If you can get it to work on Windows 11 24H, that will be great!

**Comment by semazurek** [comment]
Currently I am using 23H2 Win 11 and Win 10 (2 devices). I will download 24H2 right now.

**Comment by D1mar0n** [comment]
> Currently I am using 23H2 Win 11 and Win 10 (2 devices). I will download 24H2 right now.

Disabling telemetry works without problems on this version! The problem is caused by a tweak CPU Priority Tweaks. Everything else seems to work without problems.

**Comment by semazurek** [comment]
OK. 
It seems to me that the function responsible for displaying ET in the title bar - Processor Type 
 works the same as downloading the NOLP.txt file, I will verify it after 24H2 Win 11 tests.

I have a request for you, I know Russian, but not technical - computer. 
Would you like to help with translation? - a few main sentences.
![image](https://github.com/user-attachments/assets/c74397ae-4a5e-46b3-8fa5-164a110bba82)

**Comment by D1mar0n** [comment]
> It seems to me that the function responsible for displaying ET in the title bar - Processor Type works the same as downloading the NOLP.txt file, I will verify it after 24H2 Win 11 tests.
> 
> I have a request for you, I know Russian, but not technical - computer. Would you like to help with translation? - a few main sentences.

I'll be happy to help. I can also give you a very good tweaker, it’s not just good, it’s excellent! Unfortunately, now the author does not have time to update it for compatibility with the latest OS versions. I think you can find a lot of interesting developments for your tweaker.

**Comment by semazurek** [comment]
I checked quite often to see if other people had added anything new, so far I haven't found anything interesting, but you can send the link.

and if you can translate these few sentences, I will also be happy :)

**Comment by D1mar0n** [comment]
> I checked quite often to see if other people had added anything new, so far I haven't found anything interesting, but you can send the link.
> 
> and if you can translate these few sentences, I will also be happy :)

I have my own website and now I have to publish updates on it. On Saturday and Sunday I will be freer and can start translating. Here is the **[link](https://disk.yandex.ru/d/CMqvcp1F3QiaWL/Windows%2010%201809%2B)** to the tweaker. Interface languages ​​are Russian and English. I think you will figure it out without any problems. Name - **AutoSettingsPS**

**Comment by D1mar0n** [comment]
P.S. If it is convenient, then send me a text file to translate your tweaker. Where can I translate each point. For example: 
Power Option to Ultimate Perform - Настройка электропитания для максимальной производительности

**Comment by semazurek** [comment]
Name of functions inside not ready yet for dynamicly change size - if I made them that long in other languages like Russian, Polish visual style will glitch/crash... For now I need just main marked red sentences to translate..

And I am testing right now E.T. 5.4 on Win 11 24H2 and.... Microsoft just for no reason removed WMIC command 😂👌
I am currently working for path/changing functions.

**Comment by D1mar0n** [comment]
> OK. It seems to me that the function responsible for displaying ET in the title bar - Processor Type works the same as downloading the NOLP.txt file, I will verify it after 24H2 Win 11 tests.
> 
> I have a request for you, I know Russian, but not technical - computer. Would you like to help with translation? - a few main sentences. ![image](https://private-user-images.githubusercontent.com/85984736/366858473-c74397ae-4a5e-46b3-8fa5-164a110bba82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDUyODAsIm5iZiI6MTcyNjE0NDk4MCwicGF0aCI6Ii84NTk4NDczNi8zNjY4NTg0NzMtYzc0Mzk3YWUtNGE1ZS00NmIzLThmYTUtMTY0YTExMGJiYTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDEyNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOGJmMjk1ZmQwOTQxMDg0ZDE4MWNiMGE3Yjg2ODNlNjY4MDI0OGEzMjdkZDU1YjlmMmM4OWY4ODg4ZjdiZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lZXk8-f--XoKrkhdFdGdkUC3UomIYX0EfbAgiJxFOqc)

Translation  **[Link](https://www.upload.ee/files/17101069/Translate.txt.html)**

**Comment by semazurek** [comment]
Unselect All - Отменить выбор всех >?
Too long :c 

check and download new version Build: Public | 12.09.2024 now updated and fixed for all Win 10/11 + Win 11 24H2

**Comment by D1mar0n** [comment]
> Unselect All - Отменить выбор всех >?
Отменить всё

I'll download it now and check it out

**Comment by D1mar0n** [comment]
![2024-09-12_153121](https://github.com/user-attachments/assets/90bdae31-01f3-4492-a6f7-20a1fc05137a)

ОК !!!

**Comment by semazurek** [comment]
В настоящее время я работаю над изменением русского языка, который вы предоставили ))
как еще написать  Unselect All - ответ на все?

**Comment by D1mar0n** [comment]
> как еще написать Unselect All - ответ на все?

Отменить всё

**Comment by semazurek** [comment]
Спасибо за помощь, и я сам помогу, чем смогу, если проблема останется.

**Comment by D1mar0n** [comment]
Я если у Вас будет желание и время сделать полный твикер для всех настроек, с радостью помогу и предоставлю много интересных решений и информации для этого. Так помогу с тестированием.

If you have the desire and time to make a complete tweaker for all settings, I will be happy to help and provide many interesting solutions and information for this. So I’ll help with testing.

**Comment by D1mar0n** [comment]
Привет! Как дела? Только что решил протестировать последнюю версию Твикера. У меня сразу вылетает ошибка. Исправь пожалуйста.


На Чт.12.09.2024 15:43:27, Sebastian Mazurek ***@***.***> написал(а):
Спасибо за помощь, и я сам помогу, чем смогу, если проблема останется.

**Comment by semazurek** [comment]
Какая ошибка выскакивает?

**Comment by D1mar0n** [comment]
Не знаю как я забыл добавить скриншот,



************** Текст исключения **************
System.InvalidOperationException: Категория не существует.
   в System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   в System.Diagnostics.PerformanceCounter.InitializeImpl()
   в System.Diagnostics.PerformanceCounter.Initialize()
   в System.Diagnostics.PerformanceCounter.NextSample()
   в System.Diagnostics.PerformanceCounter.NextValue()
   в ET.Form1.GetUsedCPU()
   в ET.Form1.<timer1_Tick>b__58_0()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ET.Form1.<timer1_Tick>d__58.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ET
    Версия сборки: 5.4.1.0
    Версия Win32: 5.4.1.0
    CodeBase: file:///D:/Downloads/Compressed/New%20Folder%20With%20Items/ET-Optimizer.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9266.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.
На Ср.16.10.2024 13:38:47, Sebastian Mazurek ***@***.***> написал(а):
Reopened #24 [https://github.com/semazurek/ET-Optimizer/issues/24].

**Comment by semazurek** [comment]
В свободное время я заработаю DEBUG. После перезапуска ET все еще выскакивает ошибка?

**Comment by D1mar0n** [comment]
Эта ошибка выскакивает не при запуске твикера, а при попытке снять отметки в разделе отключения телеметрии. Я хотел оставить только отключения телеметрии в Фаерфокс.
На Чт.17.10.2024 8:02:38, Sebastian Mazurek ***@***.***> написал(а):
В свободное время я заработаю DEBUG. После перезапуска ET все еще выскакивает ошибка?

**Comment by D1mar0n** [comment]
Привет! Сейчас просто при запуске твикера вылетает эта ошибка:

Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.InvalidOperationException: Категория не существует.
   в System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   в System.Diagnostics.PerformanceCounter.InitializeImpl()
   в System.Diagnostics.PerformanceCounter.Initialize()
   в System.Diagnostics.PerformanceCounter.NextSample()
   в System.Diagnostics.PerformanceCounter.NextValue()
   в ET.Form1.GetUsedCPU()
   в ET.Form1.<timer1_Tick>b__58_0()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в ET.Form1.<timer1_Tick>d__58.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9282.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ET
    Версия сборки: 5.4.1.0
    Версия Win32: 5.4.1.0
    CodeBase: file:///D:/Downloads/Programs/ET-Optimizer_2.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9282.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

На Вс.03.11.2024 18:54:12, Sebastian Mazurek ***@***.***> написал(а):
Closed #24 [https://github.com/semazurek/ET-Optimizer/issues/24] as completed.

**Comment by semazurek** [comment]
Эта ошибка странная. Потому что ни одна функция не была изменена с предыдущей работающей версии. И один раз я заметил бледный, но после повторного запуска он исчез, и один раз он выскочил, а во второй раз он больше не появлялся. И получается, что функция, отвечающая за измерение % процессора, высыпается или что-то блокирует его.

**Comment by semazurek** [comment]
До сих пор я не видел, чтобы что-то не дало работе всего приложения, а сама бледность не отображается, поэтому я не знаю, в чем дело.

**Comment by semazurek** [comment]
Он работает над исправлением, чтобы было легче перевести все приложения на другие языки.

**Comment by semazurek** [comment]
Если хотите помочь, вот список, который нужно перевести на русский:
(не может быть длиннее оригинала, необходимы краткие описания.)

chck1.Text = "Disable Edge WebWidget";
chck2.Text = "Power Option to Ultimate Perform.";
chck3.Text = "Split Threshold for Svchost";
chck4.Text = "Dual Boot Timeout 3sec";
chck5.Text = "Disable Hibernation/Fast Startup";
chck6.Text = "Disable Windows Insider Experiments";
chck7.Text = "Disable App Launch Tracking";
chck8.Text = "Disable Powerthrottling (Intel 6gen+)";
chck9.Text = "Turn Off Background Apps";
chck10.Text = "Disable Sticky Keys Prompt";
chck11.Text = "Disable Activity History";
chck12.Text = "Disable Updates for MS Store Apps";
chck13.Text = "SmartScreen Filter for Apps Disable";
chck14.Text = "Let Websites Provide Locally";
chck15.Text = "Fix Microsoft Edge Settings";
chck64.Text = "Disable Nagle's Alg. (Delayed ACKs)";
chck65.Text = "CPU Priority Tweaks";
chck16.Text = "Disable Location Sensors";
chck17.Text = "Disable WiFi HotSpot Auto-Sharing";
chck18.Text = "Disable Shared HotSpot Connect";
chck19.Text = "Updates Notify to Sched. Restart";
chck20.Text = "P2P Update Setting to LAN (local)";
chck21.Text = "Set Lower Shutdown Time (2sec)";
chck22.Text = "Remove Old Device Drivers";
chck23.Text = "Disable Get Even More Out of...";
chck24.Text = "Disable Installing Suggested Apps";
chck25.Text = "Disable Start Menu Ads/Suggestions";
chck26.Text = "Disable Suggest Apps WindowsInk";
chck27.Text = "Disable Unnecessary Components";
chck28.Text = "Defender Scheduled Scan Nerf";
chck29.Text = "Disable Process Mitigation";
chck30.Text = "Defragment Indexing Service File";
chck66.Text = "Disable Spectre/Meltdown";
chck67.Text = "Disable Windows Defender";
chck31.Text = "Disable Telemetry Scheduled Tasks";
chck32.Text = "Remove Telemetry/Data Collection";
chck33.Text = "Disable PowerShell Telemetry";
chck34.Text = "Disable Skype Telemetry";
chck35.Text = "Disable Media Player Usage Reports";
chck36.Text = "Disable Mozilla Telemetry";
chck37.Text = "Disable Apps Use My Advertising ID";
chck38.Text = "Disable Send Info About Writing";
chck39.Text = "Disable Handwriting Recognition";
chck40.Text = "Disable Watson Malware Reports";
chck41.Text = "Disable Malware Diagnostic Data";
chck42.Text = "Disable Reporting to MS MAPS";
chck43.Text = "Disable Spynet Defender Reporting";
chck44.Text = "Do Not Send Malware Samples";
chck45.Text = "Disable Sending Typing Samples";
chck46.Text = "Disable Sending Contacts to MS";
chck47.Text = "Disable Cortana";
chck48.Text = "Show File Extensions in Explorer";
chck49.Text = "Disable Transparency on Taskbar";
chck50.Text = "Disable Windows Animations";
chck51.Text = "Disable MRU lists (jump lists)";
chck52.Text = "Set Search Box to Icon Only";
chck53.Text = "Explorer on Start on This PC";
chck54.Text = "Remove Windows Game Bar/DVR";
chck55.Text = "Enable Service Tweaks";
chck56.Text = "Remove Bloatware (Preinstalled)";
chck57.Text = "Disable Unnecessary Startup Apps";
chck58.Text = "Clean Temp/Cache/Prefetch/Logs";
chck59.Text = "Remove News and Interests/Widgets";
chck60.Text = "Remove Microsoft OneDrive";
chck61.Text = "Disable Xbox Services";
chck62.Text = "Enable Fast/Secure DNS (1.1.1.1)";
chck63.Text = "Scan for Adware (AdwCleaner)";
chck68.Text = "Clean WinSxS Folder";
